### ISSUE TITLE
is it possible initialize class with simpler way?

### ISSUE THREAD

**Issue by ghost1372** [androllen/WpfNetCoreLocalization#1]
hi, Is it possible to create a simpler way instead of writing these 3 lines?
```
xmlns:ext="clr-namespace:WpfUtil.Extension;assembly=WpfUtil"
xmlns:resx="clr-namespace:ModuleA.Strings"
ext:Translation.ResourceManager="{x:Static resx:SR.ResourceManager}"
```
For example, read Resource files from a specific path (Asset/Lang.resx)
And instead of 3 lines, let's initialize the class with just one line

**Comment by androllen** [comment]
> hi, Is it possible to create a simpler way instead of writing these 3 lines?
> 
> ```
> xmlns:ext="clr-namespace:WpfUtil.Extension;assembly=WpfUtil"
> xmlns:resx="clr-namespace:ModuleA.Strings"
> ext:Translation.ResourceManager="{x:Static resx:SR.ResourceManager}"
> ```
> 
> For example, read Resource files from a specific path (Asset/Lang.resx)
> And instead of 3 lines, let's initialize the class with just one line

Hi~ o(*￣▽￣*)ブ
you can use this project [ScreenToGif](https://github.com/NickeManarin/ScreenToGif) include DynamicResource  
You can use this project to complete your project  if you can't wait me fix this issue  
hope it can help you!

**Comment by ghost1372** [comment]
@androllen  thank you
